### ISSUE TITLE
Rounding of seconds resulting in 60 breaks parse_time.  (...:59.9999999)

### ISSUE THREAD

**Issue by olekang** [gweis/isodate#69] opened 2021-11-12 12:57 UTC
Rounding of fractional seconds breaks when it rounds to 60.
(Presumably true for other fractions)

isodate.parse('9999-12-31T23.59.59.9999999')   <- DateTime.Max from MS .NET 

Example:
Python 3.7.3 (default, Jan 22 2021, 20:04:44)
```
>>> import isodate
>>> isodate.parse_datetime('2021-11-12T13:48:59.9999999')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python3.7/site-packages/isodate/isodatetime.py", line 56, in parse_datetime
    tmptime = parse_time(timestring)
  File "python3.7/site-packages/isodate/isotime.py", line 134, in parse_time
    tzinfo)
ValueError: second must be in 0..59
```

Verison:
```
$ pip show isodate
Name: isodate
Version: 0.6.0
<snip>
```

**Comment by olekang** [comment] 2021-11-12 13:00
Somewhat less likely to be used, but same issue.
```
isodate.parse_datetime('2020-01-01T23:59.999999999')
isodate.parse_datetime('2020-01-01T23.999999999')
```
Results in ValueError: microsecond must be in 0..999999

**Comment by hugovk** [comment] 2021-11-12 13:20
Duplicate of https://github.com/gweis/isodate/issues/53?

**Comment by olekang** [comment] 2021-11-12 13:43
Duplicate og #53. 
Which seems to be closed?

**Closed** 2021-11-12 13:42 UTC

**Comment by hugovk** [comment] 2021-11-12 14:23
#53 is open :)
